version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      libxposed:
        patterns:
          - "io.github.libxposed*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
